services:
  - type: static
    name: aqualia  # This name appears in your Render dashboard
    env: static
    buildCommand: npm run build
    staticPublishPath: ./dist
    # If your code is in a sub-folder, uncomment the line below:
    rootDir: ./frontend 
    routes:
      - source: /*
        destination: /index.html
        type: rewrite
